// 登录
export const LOGIN = 'LOGIN'
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

// 获取单位列表
export const WS_RECEIVE_UNITS = 'WS_RECEIVE_UNITS'
export const WS_SET_SEARCH_LIST = 'WS_SET_SEARCH_LIST'
export const WS_SET_ADD_WEBSITE = 'WS_SET_ADD_WEBSITE'
export const WS_RECEIVE_COMPANY = 'WS_RECEIVE_COMPANY'
export const WS_RECEIVE_COMPANY_LIST = 'WS_RECEIVE_COMPANY_LIST'

// 部门操作
export const SET_DEPARTMENT_TREE_DATA = 'SET_DEPARTMENT_TREE_DATA'
export const SET_DEPARTMENT_ALL_DATA = 'SET_DEPARTMENT_ALL_DATA'

// 人员操作
export const USER_SET_SEARCH_LIST = 'USER_SET_SEARCH_LIST'
export const USER_SET_ADD_USER = 'USER_SET_ADD_USER'
export const USER_SET_UPDATE_USER = 'USER_SET_UPDATE_USER'
export const USER_SET_COUNT_USER_PAGE = 'USER_SET_COUNT_USER_PAGE'
export const USER_GET_CERTIFICATE_TYPE = 'USER_GET_CERTIFICATE_TYPE'
export const USER_GET_EDU_TYPE = 'USER_GET_EDU_TYPE'
export const USER_GET_POLITICAL_TYPE = 'USER_GET_POLITICAL_TYPE'
export const USER_GET_SEX_TYPE = 'USER_GET_SEX_TYPE'
export const USER_RESETPASS = 'USER_RESETPASS'

// 模块操作
export const GET_MOUDLE_DATA_LEVEL_1 = 'GET_MOUDLE_DATA_LEVEL_1'
export const GET_MOUDLE_DATA_BY_PARENT = 'GET_MOUDLE_DATA_BY_PARENT'

// 岗位操作
export const POS_GET_SEARCH_LIST = 'POS_GET_SEARCH_LIST'
export const POS_SET_POSITIONTYPES = 'POS_SET_POSITIONTYPES'
export const POS_GET_ALL_POSITION = 'POS_GET_ALL_POSITION'

// 配置操作
export const CONF_GET_SEARCH_LIST = 'CONF_SET_SEARCH_LIST'
export const CONF_SET_CONFIG = 'CONF_SET_CONFIG'
export const CONF_SET_CONFTYPES = 'CONF_SET_CONFTYPES'

// 角色操作
export const ROLE_SET_SEARCH_LIST = 'ROLE_SET_SEARCH_LIST'
export const ROLE_SET_ROLETYPES = 'ROLE_SET_ROLETYPES'
export const ROLE_FIND_ALLROLE = 'ROLE_FIND_ALLROLE'

// 模块操作
export const GET_ROLEMOUDLE_TREE = 'GET_ROLEMOUDLE_TREE'
export const MOUDLE_LIST = 'MOUDLE_LIST'
export const MOUDLE_ALL = 'MOUDLE_ALL'

// 角色权限
export const ROLEMOUDLE_SET_MOUDLELIST = 'ROLEMOUDLE_SET_MOUDLELIST'

// 日志操作
export const LOG_GET_SEARCH_LIST = 'LOG_GET_SEARCH_LIST'
export const LOG_GET_LOGTYPES = 'LOG_GET_LOGTYPES'

// 获取系统字典Group列表
export const DICTIONARY_GROUP_LIST = 'DICTIONARY_GROUP_LIST'

// 获取系统字典Item列表
export const DICTIONARY_ITEM_LIST = 'DICTIONARY_ITEM_LIST'

// 系统字典Item操作
export const DICTIONARY_SET_ADD_ITEM = 'DICTIONARY_SET_ADD_ITEM'
export const DICTIONARY_SET_UPDATE_ITEM = 'DICTIONARY_SET_UPDATE_ITEM'

// 系统字典根据ID获取Item
export const DICTIONARY_ITEM_BY_ID = 'DICTIONARY_ITEM_BY_ID'
export const ALL_DICT_ITEM_BY_DICT_GROUPID = 'ALL_DICT_ITEM_BY_DICT_GROUPID'

// 已启用的系统字典Item按groupId查找
export const ALL_ENABLED_DICT_ITEM_BY_DICT_GROUPID = 'ALL_ENABLED_DICT_ITEM_BY_DICT_GROUPID'

// 运维报表-报表数据
export const OPR_DATA_REPORT_DATA = 'OPR_DATA_REPORT_DATA'

export const MONITOR_POINT_LIST = 'MONITOR_POINT_LIST'
export const MONITORING_DATA_REPORT_DATA = 'MONITORING_DATA_REPORT_DATA'
